### ISSUE TITLE
incompatible net architecture when loading states_dict

### ISSUE THREAD

**Issue by huiwenzhang** [alexsax/visual-prior#1]
Hi, 

I found there are some errors when loading some of the  pretrained model. Apparently, it's because the net architecture used for training is different with the net used for reproduction, which refers to the encoder and decoder defined in this repo. We have the same architecture for all the tasks here (except for the output layer). But  the trained model use different net architectures for some of the tasks. So maybe it is better to give a clear instruction about which task is supported by this repo.
Besides, I found this repo is pretty similar to the task bank module in the taskonomy repo. Is there any difference  between them?

Thanks

**Comment by alexsax** [comment]
Hi, thanks for the question! 

The networks here are more or less ports of the Taskonomy networks into pytorch. We’ve separated those networks into an encoder and decoder portion. The encoder portion is a ResNet50 and is the same across all tasks. The decoder portion varies but is essentially unused—you probably don’t need to interact with it very much. 

I think that we may have only ported over the single-input-image tasks (so no ego motion), and all those that we did port are listed in the README here: https://github.com/alexsax/midlevel-reps. I believe that you already found that repo. 

Let me know if this doesn’t answer your question. I’m going to close this for now, but feel free to reopen it (or ask in the main repo)
